version: '3.5'
services:
  smart-frontend:
    container_name: smartdial
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 7000:80
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true  
