version: '3.5'
services:
  dialer-agent-web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:30
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true  